In [3]:
%reload_ext autoreload
%autoreload 2

In [4]:
import numpy as np
import mne
from data_processing import compute_lags, apply_lags

In [7]:
array = np.random.randint(low=1, high=20, size=10)

array

array([ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2])

In [15]:
advances = [3,2,-1,1,-3,-2,1,-1,2,-2]
E=3
central_array_cropped = array[E:len(array)-E]
len(central_array_cropped), central_array_cropped

(4, array([4, 9, 1, 8]))

In [16]:
l=3
array[E+l:len(array)-E+l]

array([ 8,  1, 12,  2])

In [19]:
lagged_arrays

array([[[ 2, 13, 14,  8,  1, 12,  2,  4, 16,  5]],

       [[18, 18,  3,  1,  8,  1, 12,  8, 12, 13]],

       [[19,  1,  8, 16,  4,  9,  1,  2,  7,  8]],

       [[ 1,  4,  8,  9,  1,  8,  1, 13,  6,  3]],

       [[14,  4,  6,  9,  3, 16,  4, 19,  2,  6]],

       [[11, 10,  9,  3, 16,  4,  9, 19, 19,  3]],

       [[10,  8, 17,  9,  1,  8,  1, 18, 11, 10]],

       [[14,  3,  4, 16,  4,  9,  1,  7,  9,  8]],

       [[ 7,  9, 14,  1,  8,  1, 12, 11, 19, 13]],

       [[14,  3, 11,  3, 16,  4,  9,  2,  6, 19]]])

In [18]:
lagged_cropped_arrays = [array[E+l:len(array)-E+l] for l in advances]

#stuff the borders with random values
lagged_arrays =[np.concatenate([np.random.randint(low=1,high=20, size=E), lga, np.random.randint(low=1,high=20, size=E)]) for lga in lagged_cropped_arrays]

#add channel_dim
lagged_arrays = [np.expand_dims(la, axis=0) for la in lagged_arrays]

lagged_arrays = np.stack(lagged_arrays)
lagged_arrays.shape

(10, 1, 10)

In [20]:
central_arrays = np.repeat(np.expand_dims([array], axis=0),repeats=40, axis=0)
central_arrays.shape #n_epochs,n_channels,n_times

(40, 1, 10)

In [21]:
#concatenate centralized and lagged arrays
e_ = np.concatenate([central_arrays, lagged_arrays])
e_.shape, e_

((50, 1, 10),
 array([[[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9,  3, 16,  4,  9,  1,  8,  1, 12,  2]],
 
        [[ 9, 

In [22]:
info_ = mne.create_info(ch_names=1,sfreq = 50)
epochs_ = mne.EpochsArray(e_,info_)

Not setting metadata
50 matching events found
No baseline correction applied
0 projection items activated


In [23]:
# lags_list, cond_hist
lags_list, cond_hist = compute_lags(epochs_, similarity="covariance", criteria_sim="greatest_local_max", E=E)         

E:  3
Iteration num:  0


In [24]:
lags_list

[-2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -2,
 -1,
 0,
 -1,
 -1,
 1,
 2,
 -1,
 -1,
 -2,
 -2]

In [25]:
lags_list[-10:], lags

([-1, 0, -1, -1, 1, 2, -1, -1, -2, -2], [3, 5, -2, 7, -5, 4, -1, 9, -8, 8])

In [16]:
lagged_epochs_ = apply_lags(epochs_, E, [l for l in lags_list])

In [17]:
lagged_epochs_.get_data()

array([[[ 5., 11., 15., ..., 19.,  8.,  8.]],

       [[ 5., 11., 15., ..., 19.,  8.,  8.]],

       [[ 5., 11., 15., ..., 19.,  8.,  8.]],

       ...,

       [[10.,  4.,  3., ..., 19.,  8.,  8.]],

       [[ 5., 11., 15., ..., 12.,  5., 11.]],

       [[ 7., 12., 16., ..., 19.,  8.,  8.]]])

In [24]:
lagged_epochs_.get_data()[-1]

array([[ 7., 12., 16., 18., 12.,  5., 19.,  8., 14.,  2., 16.,  5., 15.,
         5., 14.,  8., 11.,  5.,  8., 15.,  2.,  4., 10.,  1., 19., 13.,
         6., 15., 19.,  1., 13., 16.,  1.,  8.,  4.,  5., 15.,  9., 10.,
        19.,  7.,  8.,  9., 14.,  5.,  5., 13., 19.,  8.,  8.]])

In [25]:
lagged_epochs_.get_data()[-1]

array([[ 7., 12., 16., 18., 12.,  5., 19.,  8., 14.,  2., 16.,  5., 15.,
         5., 14.,  8., 11.,  5.,  8., 15.,  2.,  4., 10.,  1., 19., 13.,
         6., 15., 19.,  1., 13., 16.,  1.,  8.,  4.,  5., 15.,  9., 10.,
        19.,  7.,  8.,  9., 14.,  5.,  5., 13., 19.,  8.,  8.]])

In [26]:
lagged_arrays[-1]

array([[19, 15,  7, 12, 16, 18, 12,  5, 19,  8, 14,  2, 16,  5, 15,  5,
        14,  8, 11,  5,  8, 15,  2,  4, 10,  1, 19, 13,  6, 15, 19,  1,
        13, 16,  1,  8,  4,  5, 15,  9, 10, 19,  7,  8,  9, 14,  5,  5,
        13, 19,  8,  8,  9,  2, 15,  7, 17, 15, 10,  4, 17, 10,  4, 18,
        11,  3,  6,  1, 12,  4]])

In [19]:
lagged_epochs_.get_data()[0]

array([[ 5., 11., 15., 15., 13.,  9., 17.,  7., 14.,  2., 16.,  5., 15.,
         5., 14.,  8., 11.,  5.,  8., 15.,  2.,  4., 10.,  1., 19., 13.,
         6., 15., 19.,  1., 13., 16.,  1.,  8.,  4.,  5., 15.,  9., 10.,
        19.,  7.,  8.,  9., 14.,  5.,  5., 13., 19.,  8.,  8.]])

In [28]:
len(lagged_epochs_.get_data()[0].ravel())

50

In [32]:
len(e_[0].ravel())
e_[0]

array([[11,  8, 12,  9,  8, 17,  7, 10, 16, 13,  5, 11, 15, 15, 13,  9,
        17,  7, 14,  2, 16,  5, 15,  5, 14,  8, 11,  5,  8, 15,  2,  4,
        10,  1, 19, 13,  6, 15, 19,  1, 13, 16,  1,  8,  4,  5, 15,  9,
        10, 19,  7,  8,  9, 14,  5,  5, 13, 19,  8,  8,  9,  2, 15,  7,
        17, 15, 10,  4,  7, 14]])

In [33]:
central_array_cropped

array([ 5, 11, 15, 15, 13,  9, 17,  7, 14,  2, 16,  5, 15,  5, 14,  8, 11,
        5,  8, 15,  2,  4, 10,  1, 19, 13,  6, 15, 19,  1, 13, 16,  1,  8,
        4,  5, 15,  9, 10, 19,  7,  8,  9, 14,  5,  5, 13, 19,  8,  8])