In [1]:
%reload_ext autoreload
%autoreload 2

In [11]:
import numpy as np
import mne
from data_processing import compute_lags, apply_lags

In [3]:
array = np.random.randint(low=1, high=20, size=70)

lags = [3,5,-2,7,-5,4,-1,9,-8,8]
E=10
central_array_cropped = array[E:len(array)-E]
len(central_array_cropped), central_array_cropped

(50,
 array([ 3,  9, 19,  9,  3,  6,  5, 14, 11,  7, 10,  4,  6,  1, 14,  5,  3,
        16,  8,  4,  1,  3, 11,  7,  8,  6, 19,  8,  3, 10,  5,  4,  2, 11,
         4,  9,  5,  6, 12, 13,  7,  1,  2, 19, 10, 14,  3,  6,  7,  6]))

In [34]:
array

array([15, 10, 14, 13,  1,  8,  6,  4, 12, 11,  3,  9, 19,  9,  3,  6,  5,
       14, 11,  7, 10,  4,  6,  1, 14,  5,  3, 16,  8,  4,  1,  3, 11,  7,
        8,  6, 19,  8,  3, 10,  5,  4,  2, 11,  4,  9,  5,  6, 12, 13,  7,
        1,  2, 19, 10, 14,  3,  6,  7,  6,  8, 11, 10,  1, 15, 14, 13, 19,
       19, 10])

In [35]:
l=3
array[E+l:len(array)-E+l]

array([ 9,  3,  6,  5, 14, 11,  7, 10,  4,  6,  1, 14,  5,  3, 16,  8,  4,
        1,  3, 11,  7,  8,  6, 19,  8,  3, 10,  5,  4,  2, 11,  4,  9,  5,
        6, 12, 13,  7,  1,  2, 19, 10, 14,  3,  6,  7,  6,  8, 11, 10])

In [21]:
lagged_cropped_arrays = [array[E+l:len(array)-E+l] for l in lags]

#stuff the borders with random values
lagged_arrays =[np.concatenate([np.random.randint(low=1,high=20, size=E), lga, np.random.randint(low=1,high=20, size=E)]) for lga in lagged_cropped_arrays]

#add channel_dim
lagged_arrays = [np.expand_dims(la, axis=0) for la in lagged_arrays]

lagged_arrays = np.stack(lagged_arrays)
lagged_arrays.shape

(10, 1, 70)

In [22]:
central_arrays = np.repeat(np.expand_dims([array], axis=0),repeats=40, axis=0)
central_arrays.shape #n_epochs,n_channels,n_times

(40, 1, 70)

In [23]:
#concatenate centralized and lagged arrays
e_ = np.concatenate([central_arrays, lagged_arrays])
e_.shape, e_

((50, 1, 70),
 array([[[15, 10, 14, ..., 19, 19, 10]],
 
        [[15, 10, 14, ..., 19, 19, 10]],
 
        [[15, 10, 14, ..., 19, 19, 10]],
 
        ...,
 
        [[ 5,  9,  6, ...,  2,  9, 16]],
 
        [[14,  9,  9, ...,  4, 15,  4]],
 
        [[ 3, 12, 13, ...,  5,  8,  5]]]))

In [24]:
info_ = mne.create_info(ch_names=1,sfreq = 50)
epochs_ = mne.EpochsArray(e_,info_)

Not setting metadata
50 matching events found
No baseline correction applied
0 projection items activated


In [42]:
# lags_list, cond_hist
lags_list, cond_hist = compute_lags(epochs_, similarity="covariance", criteria_sim="greatest_local_max", E=E)         

E:  10
Iteration num:  0


In [43]:
lags_list

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 5,
 -2,
 7,
 -5,
 4,
 -1,
 9,
 -8,
 8]

In [44]:
lags_list[-10:], lags

([3, 5, -2, 7, -5, 4, -1, 9, -8, 8], [3, 5, -2, 7, -5, 4, -1, 9, -8, 8])